FROM mcr.microsoft.com/dotnet/sdk:10.0 AS migrations
WORKDIR /src

ENV PATH="${PATH}:/root/.dotnet/tools"

RUN dotnet tool install --global dotnet-ef --version 10.0.4

COPY backend.csproj ./
RUN dotnet restore ./backend.csproj

COPY . ./
RUN dotnet build ./backend.csproj -c Release --no-restore

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "backend.csproj", "--configuration", "Release", "--no-build"]
